- name: Initial configuration
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Install python3 on Fedora
      raw: test -e /bin/python3 || (grep -q "assumeyes=1" /etc/dnf/dnf.conf || echo "assumeyes=1" >> /etc/dnf/dnf.conf && dnf update && dnf install python3 iproute)
      ignore_errors: yes
    - name: Install python3 on Debian/Ubuntu
      raw: test -e /bin/python3 || (apt-get update && apt-get -y install python3 python3-apt iproute2)
      ignore_errors: yes  

- name: Starting basic-configuration role
  hosts: all
  gather_facts: true
  vars_prompt:
    - name: username
      prompt: "Zadaj meno noveho uzivatela"
      private: no
    - name: password
      prompt: "Zadaj heslo pre noveho uzivatela"
  roles:
    - role: basic-configuration